name: push code
on: 
  push: 
    branches: 
      - main # è¿™é‡Œè¡¨ç¤ºpushåˆ°mainåˆ†æ”¯å°±ä¼šè§¦å‘æµç¨‹
  workflow_dispatch:    
jobs:
  deploy_job:
    runs-on: ubuntu-20.04
    steps:
      # è¿™æ˜¯githubå®˜æ–¹çš„ä¸€ä¸ªactionï¼Œç”¨äºcloneè¯¥ä»“åº“çš„æºç åˆ°å·¥ä½œæµä¸­ï¼Œ
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
    # å®‰è£… sed å·¥å…·
    #  - name: Install Sed Tool (Optional)
    #    run: sudo apt update && sudo apt install -y sed
    # è¿æ¥åˆ°sshï¼Œå¹¶ä¸”åšä¸€ä¸ªæ‹·è´æ“ä½œçš„action
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        env:
         # æœ¬åœ°.sshæ–‡ä»¶ä¸‹çš„ç§é’¥id_rsaï¼Œå­˜åœ¨secretsçš„PRIVATE_KEYä¸­
         SSH_PRIVATE_KEY: ${{ secrets.KEY_DEBIAN}}
          # å¤åˆ¶æ“ä½œçš„å‚æ•°ã€‚"-avzr --delete"æ„å‘³éƒ¨ç½²æ—¶æ¸…ç©ºæœåŠ¡å™¨ç›®æ ‡ç›®å½•ä¸‹çš„æ–‡ä»¶
         ARGS: "-avzr --delete" 
          # æºç›®å½•ï¼Œç›¸å¯¹äº$GITHUB_WORKSPACEæ ¹ç›®å½•çš„è·¯å¾„
         SOURCE: "app/"
          # æœåŠ¡å™¨åŸŸå/IP
         REMOTE_HOST: ${{ secrets.SSH_HOST }}
          # æœåŠ¡å™¨ç”¨æˆ·å
         REMOTE_USER:  ${{ secrets.SSH_USER }}
          # ç›®æ ‡ç›®å½•
         TARGET: '/home/www/hipy/app'
          # æ’é™¤ç›®å½•
         EXCLUDE: "configs,db/hipy.db,main.py"
         SCRIPT_BEFORE: docker stop hipy-server
         SCRIPT_AFTER: |
          chmod -R 777 /home/www/hipy/app
          docker restart hipy-server
